### ISSUE TITLE
Speech Command list

### ISSUE THREAD

**Issue by NEONKID** [amathon-2019/MLCodeEditor#4]
@ingyeoking13 
기본적으로 이번 프로젝트에서 주어졌던 6개의 음성 명령입니다.
1. 맨 위로 / 맨 아래로
2. 스크롤 내려 / 스크롤 올려
3. 저장하기 / 저장하고 나가기

추가적으로 이런 것도 넣었으면 하는 리스트입니다.
1. 특정 단어 검색해 줘.
    - 코드 에디터에서 구현된 검색 기능을 통한 응용
2. 확대하기 / 축소하기 
    - 이 부분은 마우스 핸들러를 이용해서 Ctrl + wheel 구현하는 것도 포함하면 괜찮을 듯합니다.

@adbr-dev  이 외에 또 다른 사항이 있다면 댓글을 남겨주세요.

**Comment by adbr-dev** [comment]
주제 1 : 머신러닝 기반 음성인식 데스크탑 코드 에디터 만들기(저장하고 나가기, 나가기, 맨 위로, 맨 아래로 등 구현)

- 맨위로
- 맨아래로
- 저장하기
- 저장하고 나가기
- 확대하기
- 축소하기

**Comment by adbr-dev** [comment]
- 저장하기
-- save
-  저장하고 나가기
-- saveAsExit
- 맨위로
-- moveTop
- 맨아래로
-- moveBottom
- 확대하기
-- zoomIn 
- 축소하기
-- zoomOut
- 이 외 나머지
-- none
